/** @file sumo_exporter.js
 * @author Authored in 2020 at <https://github.com/nicky-nym/city3d>
 * @license UNLICENSE
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 */

/**
 * SumoExporter can create and download XML files the SUMO traffic similator.
 * For more about SUMO, see https://sumo.dlr.de/
 */
class SumoExporter {
  /**
   * Creates an exporter instance that can generate SUMO xml files for a model.
   * @param {City.Model} model - a CITY.Model instance
   */
  constructor (model) {
    this._model = model
  }

  _downloadTextFile (filename, contentText) {
    this._downloadFile(filename, 'text/plain', contentText)
  }

  _downloadXmlFile (filename, contentText) {
    this._downloadFile(filename, 'text/xml', contentText)
  }

  _downloadFile (filename, datatype, contentText) {
    const element = document.createElement('a')
    element.setAttribute('download', filename)
    element.setAttribute('href', 'data:' + datatype + ';charset=utf-8,' + encodeURIComponent(contentText))
    element.style.display = 'none'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  exportFiles () {
    this._downloadTextFile(
      'city3d.READMET.txt',
`This file, and the 4 other city3d.* files here, were generated by a city3d web app 
For more about the city3d app, see https://github.com/nicky-nym/city3d#readme

These files are for running traffic simulations using SUMO.
For more about SUMO, see https://sumo.dlr.de/

If you have SUMO installed, you can run these files using these commands:
$ netconvert --node-files=city3d.nod.xml --edge-files=city3d.edg.xml --output-file=city3d.net.xml
$ sumo -c city3d.sumocfg`
    )

    this._downloadXmlFile(
      'city3d.nod.xml',
`<nodes>
  <node id="1" x="-250.0" y="0.0" />
  <node id="2" x="+250.0" y="0.0" />
  <node id="3" x="+251.0" y="0.0" />
</nodes>`
    )

    this._downloadXmlFile(
      'city3d.edg.xml',
`<edges>
  <edge from="1" id="1to2" to="2" />
  <edge from="2" id="out" to="3" />
</edges>`
    )

    this._downloadXmlFile(
      'city3d.rou.xml',
`<routes>
  <vType accel="1.0" decel="5.0" id="Car" length="2.0" maxSpeed="100.0" sigma="0.0" />
  <route id="route0" edges="1to2 out"/>
  <vehicle depart="1" id="veh0" route="route0" type="Car" />
</routes>`
    )

    this._downloadXmlFile(
      'city3d.sumocfg',
`<configuration>
  <input>
    <net-file value="city3d.net.xml"/>
    <route-files value="city3d.rou.xml"/>
  </input>
  <time>
    <begin value="0"/>
    <end value="10000"/>
  </time>
</configuration>`
    )

    this._downloadXmlFile(
      'city3d.net.xml',
`<?xml version="1.0" encoding="UTF-8"?>
<net version="1.3" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="250.00,0.00" convBoundary="0.00,0.00,501.00,0.00" origBoundary="-250.00,0.00,251.00,0.00" projParameter="!"/>

    <edge id=":2_0" function="internal">
        <lane id=":2_0_0" index="0" speed="13.89" length="0.10" shape="500.00,-1.60 500.00,-1.60"/>
    </edge>

    <edge id="1to2" from="1" to="2" priority="-1">
        <lane id="1to2_0" index="0" speed="13.89" length="500.00" shape="0.00,-1.60 500.00,-1.60"/>
    </edge>
    <edge id="out" from="2" to="3" priority="-1">
        <lane id="out_0" index="0" speed="13.89" length="1.00" shape="500.00,-1.60 501.00,-1.60"/>
    </edge>

    <junction id="1" type="dead_end" x="0.00" y="0.00" incLanes="" intLanes="" shape="0.00,0.00 0.00,-3.20"/>
    <junction id="2" type="priority" x="500.00" y="0.00" incLanes="1to2_0" intLanes=":2_0_0" shape="500.00,0.00 500.00,-3.20 500.00,0.00">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="3" type="dead_end" x="501.00" y="0.00" incLanes="out_0" intLanes="" shape="501.00,-3.20 501.00,0.00"/>

    <connection from="1to2" to="out" fromLane="0" toLane="0" via=":2_0_0" dir="s" state="M"/>

    <connection from=":2_0" to="out" fromLane="0" toLane="0" dir="s" state="M"/>

</net>`
    )
  }
}

export { SumoExporter }
